#!/usr/bin/env bash
#prints from 1 to 10, bad  luck for 4th, good luck for 8, best school for everything else
i=1;
while [ $i -le 10 ]; do
	if [ $i == 4 ]; then
		echo "bad luck"
	elif [ $i == 8 ]; then 
		echo "good luck"
	else 
		echo "Best School"
	fi; ((i++))  ; done
