#!/usr/bin/env bash
#from 1 to 20, 4 China, 9 Japan, 17 Italy bad luck
i=1;
while [ $i -le 20 ]; do
	echo $i
	case $i in
		4) echo "bad luck from China" ;;
		8) echo "bad luck from Japan" ;;
		17) echo "bad luck from Italy" ;;

	esac
	((i++))
done
