#!/usr/bin/env bash
#process and pid file


PIDFILE="/var/run/myscript.pid"


if ! touch "$PIDFILE" 2>/dev/null; then
    PIDFILE="/tmp/myscript.pid"
fi
echo $$ > "$PIDFILE"
handle_sigterm() {
    echo "I hate the kill command"
    cleanup_and_exit
}

handle_sigint() {
    echo "Y U no love me?!"
}

handle_sigquit() {
    cleanup_and_exit
}

cleanup_and_exit() {
    rm -f "$PIDFILE"
    exit 0
}


trap handle_sigterm SIGTERM
trap handle_sigint SIGINT
trap handle_sigquit SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 1
done
