#!/usr/bin/env bash
#process and pid file
file="/var/run/myscript.pid"
echo $$ | sudo tee "$file" > /dev/null
trap 'echo "I hate the kill command"' SIGTERM 
trap 'echo "Y U no love me?!"' SIGINT 
terminateItself() {
	rm -rf $file
	exit 0
}
trap terminateItself SIGQUIT SIGTERM 


while true; do
	echo "To infinity and beyond"
	sleep 2
done

