#!/usr/bin/env bash
#kill without kill or killall


if pgrep "4-to_infinity_and_beyond" > /dev/null; then
  echo "Stopping 4-to_infinity_and_beyond..."
  pkill "4-to_infinity_and_beyond"
  echo "Process stopped."
else
  echo "Process 4-to_infinity_and_beyond not running."
fi
